- hosts: all
  remote_user: root
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - net-tools
        - tmux
        - dpkg
        - wget
        - curl
        - neofetch
        - git
        - cockpit
        - tuned
        - tuned-utils
        - lm-sensors
