- hosts: all
  remote_user: root
  tasks:
  - name: Update apt cache package list
    apt:
      update_cache: yes

  - name: Install a list of packages
    apt:
      pkg:
      - net-tools
      - tmux
      - dpkg
      - wget
      - curl
      - neofetch
      - git
      - cockpit
      - cockpit-docker
      - tuned
      - tuned-utils
      - lm-sensors
