- hosts: school-nodes
  remote_user: root
  tasks:

  - name: Remove a list of apt packages
    apt:
      name: "{{ packages }}"
      state: absent
      update_cache: no
    vars:
      packages:
        - unity-webapps-common

  - name: Install a list of apt packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - backintime-gnome
        - conky
        - gnome-tweaks
        - libcanberra-gtk-module
        - vim-gtk

  #   - name: Remove a list of snap packages
  #     apt:
  #       name: "{{ packages }}"
  #       state: absent
  #       update_cache: no
  #     vars:
  #       packages:
  #         - google-play-music-desktop-player
  #
  # - name: Install a list of snap packages
  #    snap:
  #        name: "{{ snap_packages }}"
  #        state: present
  #      vars:
  #        snap_packages:
  #          - lxd
  #          - chromium
  #          - gimp
  #          - signal-desktop
  #          - vlc
  #
  #    - name: Install a list of snap packages with option "--classic"
  #      snap:
  #        name: "{{ snap_packages }}"
  #        state: present
  #        classic: yes
  #      vars:
  #        snap_packages:
  #          - code
  #          - helm
  #          - juju
