- hosts: server-nodes
  connection: local
  remote_user: root
  tasks:

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Install a list of apt packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - net-tools
        - tmux
        - dpkg
        - wget
        - curl
        - neofetch
        - git
        - cockpit
        - cockpit-docker
        - tuned
        - tuned-utils
        - lm-sensors
